"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {Plus,FolderKanban,CheckCheck,Circle,CircleDashed,AlertCircle,Pencil,LogOut,RotateCw,ArrowUpRight,CalendarDays,Layers3} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Empty,EmptyDescription,EmptyHeader,EmptyMedia,EmptyTitle} from "@/components/ui/empty";
import {Skeleton} from "@/components/ui/skeleton";
import {Progress} from "@/components/ui/progress";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {statusLabels,type Project,type Task,type TaskDraft,type Status} from "@/lib/model";
import {registerWorkspaceTools} from "@/lib/webmcp";

const sessionExpiredMessage="Η σύνδεσή σου έληξε. Συνδέσου ξανά για να συνεχίσεις.";
const blank:TaskDraft={title:"",notes:"",assignee:"",due_date:null,status:"OPEN"};
async function api<T>(path:string,options:RequestInit={}):Promise<T>{
  const r=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest",...options.headers},cache:"no-store"});
  if(r.status===401)throw new Error(sessionExpiredMessage);
  const d=(await r.json().catch(()=>({error:"Η υπηρεσία δεν απάντησε. Δοκίμασε ξανά."}))) as T & {error?:string};
  if(!r.ok)throw new Error(d.error||"Η ενέργεια δεν ολοκληρώθηκε.");return d;
}
function dateLabel(v:string|null){return v?new Intl.DateTimeFormat("el-GR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v+"T12:00:00")):"Χωρίς ημερομηνία";}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}

export default function Workspace({user,environment}:{user:{name:string;email:string};environment:string}){
  const [projects,setProjects]=useState<Project[]>([]),[tasks,setTasks]=useState<Task[]>([]);
  const [projectId,setProjectId]=useState(""),[loading,setLoading]=useState(true),[taskLoading,setTaskLoading]=useState(false),[error,setError]=useState("");
  const [projectOpen,setProjectOpen]=useState(false),[taskOpen,setTaskOpen]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState("");
  const [projectDraft,setProjectDraft]=useState({name:"",description:""});
  const [draft,setDraft]=useState<TaskDraft>(blank),[editing,setEditing]=useState<Task|null>(null);
  const req=useRef(0),selected=useRef(projectId);selected.current=projectId;
  const active=projects.find(p=>p.id===projectId);
  const loadProjects=useCallback(async()=>{setLoading(true);setError("");try{const d=await api<{projects:Project[]}>("/api/projects");setProjects(d.projects);setProjectId(old=>d.projects.some(p=>p.id===old)?old:d.projects[0]?.id||"");}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
  const loadTasks=useCallback(async(id:string)=>{const seq=++req.current;setTaskLoading(true);setError("");try{const d=await api<{tasks:Task[]}>(`/api/tasks?project_id=${encodeURIComponent(id)}`);if(seq===req.current)setTasks(d.tasks);}catch(e){if(seq===req.current)setError((e as Error).message);}finally{if(seq===req.current)setTaskLoading(false);}},[]);
  useEffect(()=>{void loadProjects();},[loadProjects]);
  useEffect(()=>{setTasks([]);if(projectId)void loadTasks(projectId);else{req.current++;setTaskLoading(false);}},[projectId,loadTasks]);
  const createProject=useCallback(async(input:{name:string;description:string})=>{const d=await api<{project:Project}>("/api/projects",{method:"POST",body:JSON.stringify(input)});setProjects(p=>[d.project,...p]);setProjectId(d.project.id);return d.project;},[]);
  const createTask=useCallback(async(id:string,input:TaskDraft)=>{const d=await api<{task:Task}>("/api/tasks",{method:"POST",body:JSON.stringify({...input,project_id:id})});if(selected.current===id)setTasks(t=>[d.task,...t]);return d.task;},[]);
  const updateTask=useCallback(async(task:Task,input:TaskDraft)=>{const d=await api<{task:Task}>(`/api/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify({...input,version:task.version})});if(selected.current===task.project_id)setTasks(t=>t.map(x=>x.id===d.task.id?d.task:x));return d.task;},[]);
  useEffect(()=>registerWorkspaceTools({listProjects:()=>api("/api/projects"),createProject,createTask}),[createProject,createTask]);
  async function saveProject(e:FormEvent){e.preventDefault();setSaving(true);setFormError("");try{await createProject(projectDraft);setProjectOpen(false);setProjectDraft({name:"",description:""});toast.success("Το έργο δημιουργήθηκε.");}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}
  async function saveTask(e:FormEvent){e.preventDefault();if(!projectId)return;setSaving(true);setFormError("");try{if(editing)await updateTask(editing,draft);else await createTask(projectId,draft);setTaskOpen(false);toast.success("Η εργασία αποθηκεύτηκε.");}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}
  function openTask(t?:Task){setEditing(t??null);setDraft(t?{title:t.title,notes:t.notes,assignee:t.assignee,due_date:t.due_date,status:t.status}:{...blank});setFormError("");setTaskOpen(true);}
  const done=tasks.filter(t=>t.status==="DONE").length,progress=tasks.length?Math.round(done/tasks.length*100):0;
  const stats=[{status:"OPEN",icon:Circle},{status:"IN_PROGRESS",icon:CircleDashed},{status:"BLOCKED",icon:AlertCircle},{status:"DONE",icon:CheckCheck}] as const;
  const newProject=()=>{setFormError("");setProjectOpen(true);};
  return <><Toaster position="bottom-right"/><header className="app-header"><a className="brand" href="/"><span className="brand-mark">D</span><span>Delivery<span className="brand-light">Desk</span></span></a><div className="header-right"><span className={`environment ${environment==="UAT"?"uat":""}`}>{environment==="UAT"?"Δοκιμές · UAT":"Προσωπικός χώρος"}</span><span className="user-name" title={user.email}>{user.name}</span><a className="logout" href="/cdn-cgi/access/logout" target="_top" aria-label="Αποσύνδεση"><LogOut size={18}/></a></div></header>
  <main className="workspace"><div className="workspace-heading"><div><p className="eyebrow">PROJECT WORKSPACE</p><h1>Από το πλάνο στην πράξη.</h1><p className="muted">Έργα, υπεύθυνοι και επόμενες ενέργειες.</p></div><Button className="primary-button" onClick={newProject}><Plus size={18}/>Νέο έργο</Button></div>
  {environment==="UAT"&&<div className="uat-notice">Περιβάλλον δοκιμών. Τα δεδομένα εδώ αποθηκεύονται ξεχωριστά.</div>}
  {error&&<div className="error-notice" role="alert"><AlertCircle size={18}/><span>{error} {error===sessionExpiredMessage&&<a className="underline" href="/">Σύνδεση ξανά</a>}</span><Button variant="outline" onClick={()=>projectId?void loadTasks(projectId):void loadProjects()}>Δοκιμή ξανά</Button></div>}
  {loading?<div className="loading-grid" aria-label="Φόρτωση έργων"><Skeleton className="h-14 w-full"/><Skeleton className="h-64 w-full"/></div>:!projects.length?<section className="first-project"><div className="first-project-copy"><span className="step-number">01 / ΕΝΑΡΞΗ</span><h2>Κάθε παραδοτέο<br/>ξεκινά με ένα έργο.</h2><p>Δώσε ένα όνομα στο έργο σου. Στη συνέχεια, πρόσθεσε εργασίες, όρισε υπεύθυνους και παρακολούθησε την πρόοδο.</p><Button className="primary-button" onClick={newProject}>Δημιουργία πρώτου έργου<ArrowUpRight size={18}/></Button></div><div className="empty-project-detail"><FolderKanban size={42} strokeWidth={1.4}/><span>Ο χώρος σου είναι έτοιμος</span><p>Οι εργασίες σου θα εμφανίζονται εδώ.</p></div></section>:<>
  <section className="project-bar"><div className="project-picker"><span className="project-icon"><FolderKanban size={23}/></span><div><label className="field-caption" htmlFor="project-select">Ενεργό έργο</label><Select value={projectId} onValueChange={setProjectId}><SelectTrigger id="project-select" className="project-select"><SelectValue/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div></div><div className="project-progress"><span>{done} από {tasks.length} ολοκληρωμένες <strong>{progress}%</strong></span><Progress value={progress} aria-label="Πρόοδος έργου"/></div></section>
  {active?.description&&<p className="project-description">{active.description}</p>}
  <section className="stats-grid" aria-label="Κατάσταση εργασιών">{stats.map(({status,icon:Icon})=><div className={`stat-card stat-${status}`} key={status}><span className="stat-label"><Icon size={18}/>{statusLabels[status]}</span><strong>{taskLoading?"—":tasks.filter(t=>t.status===status).length}</strong></div>)}</section>
  <section className="tasks-panel"><div className="panel-heading"><div><h2>Εργασίες <span className="count">{tasks.length}</span></h2><p className="muted">Η επόμενη ενέργεια, με ξεκάθαρο owner.</p></div><div className="panel-actions"><Button variant="ghost" size="icon" aria-label="Ανανέωση εργασιών" disabled={taskLoading} onClick={()=>void loadTasks(projectId)}><RotateCw size={18}/></Button><Button className="primary-button" onClick={()=>openTask()}><Plus size={18}/>Νέα εργασία</Button></div></div>
  {taskLoading?<div className="task-loading" aria-label="Φόρτωση εργασιών"><Skeleton className="h-12 w-full"/><Skeleton className="h-12 w-full"/></div>:!tasks.length?<Empty className="task-empty"><EmptyHeader><EmptyMedia variant="icon"><Layers3/></EmptyMedia><EmptyTitle>Το πλάνο αρχίζει εδώ</EmptyTitle><EmptyDescription>Πρόσθεσε την πρώτη εργασία για το «{active?.name}».</EmptyDescription></EmptyHeader><Button variant="outline" onClick={()=>openTask()}>Προσθήκη εργασίας</Button></Empty>:<><div className="desktop-table"><Table><TableHeader><TableRow><TableHead>Εργασία</TableHead><TableHead>Owner</TableHead><TableHead>Προθεσμία</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Ενέργειες</span></TableHead></TableRow></TableHeader><TableBody>{tasks.map(t=><TableRow key={t.id}><TableCell className="task-title-cell"><button className="task-title" onClick={()=>openTask(t)}>{t.title}</button>{t.notes&&<p className="task-note">{t.notes}</p>}</TableCell><TableCell><span className="owner-cell">{t.assignee&&<span className="avatar">{t.assignee.slice(0,1).toUpperCase()}</span>}{t.assignee||"Δεν έχει οριστεί"}</span></TableCell><TableCell><span className={`due-date ${t.due_date&&t.due_date<today()&&t.status!=="DONE"?"overdue":""}`}><CalendarDays size={15}/>{dateLabel(t.due_date)}</span></TableCell><TableCell><span className={`status-badge status-${t.status}`}>{statusLabels[t.status]}</span></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Επεξεργασία ${t.title}`} onClick={()=>openTask(t)}><Pencil size={16}/></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="mobile-tasks">{tasks.map(t=><button className="mobile-task" key={t.id} onClick={()=>openTask(t)}><span className={`status-badge status-${t.status}`}>{statusLabels[t.status]}</span><strong>{t.title}</strong><span>{t.assignee||"Owner: δεν έχει οριστεί"}</span><span className={t.due_date&&t.due_date<today()&&t.status!=="DONE"?"overdue":""}>{dateLabel(t.due_date)}</span></button>)}</div></>}
  </section></>}
  <footer className="workspace-footer"><span>Delivery Desk</span><span>{environment==="UAT"?"Περιβάλλον δοκιμών":"Ο προσωπικός σου χώρος διαχείρισης έργων"}</span></footer></main>
  <Dialog open={projectOpen} onOpenChange={v=>{if(!saving)setProjectOpen(v);}}><DialogContent className="edit-dialog" showCloseButton={!saving}><DialogHeader><DialogTitle>Νέο έργο</DialogTitle><DialogDescription>Όρισε το έργο που θέλεις να παρακολουθήσεις.</DialogDescription></DialogHeader><form onSubmit={saveProject} className="edit-form"><label htmlFor="project-name">Όνομα έργου<input id="project-name" autoFocus required maxLength={120} value={projectDraft.name} onChange={e=>setProjectDraft({...projectDraft,name:e.target.value})} placeholder="π.χ. Αναβάθμιση εφαρμογής"/></label><label htmlFor="project-description">Περιγραφή <span className="optional">προαιρετικό</span><textarea id="project-description" maxLength={1000} rows={3} value={projectDraft.description} onChange={e=>setProjectDraft({...projectDraft,description:e.target.value})} placeholder="Σκοπός και βασικό scope"/></label>{formError&&<p className="form-error" role="alert">{formError} {formError===sessionExpiredMessage&&<a className="underline" href="/">Σύνδεση ξανά</a>}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setProjectOpen(false)}>Ακύρωση</Button><Button type="submit" disabled={saving}>{saving?"Αποθήκευση…":"Δημιουργία έργου"}</Button></div></form></DialogContent></Dialog>
  <Dialog open={taskOpen} onOpenChange={v=>{if(!saving)setTaskOpen(v);}}><DialogContent className="edit-dialog" showCloseButton={!saving}><DialogHeader><DialogTitle>{editing?"Επεξεργασία εργασίας":"Νέα εργασία"}</DialogTitle><DialogDescription>{active?.name}</DialogDescription></DialogHeader><form onSubmit={saveTask} className="edit-form"><label htmlFor="task-title">Εργασία<input id="task-title" autoFocus required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Τι χρειάζεται να ολοκληρωθεί;"/></label><div className="form-grid"><label htmlFor="task-owner">Owner<input id="task-owner" maxLength={120} value={draft.assignee} onChange={e=>setDraft({...draft,assignee:e.target.value})} placeholder="Όνομα υπεύθυνου"/></label><label htmlFor="task-due">Προθεσμία<input id="task-due" type="date" min="1900-01-01" max="2100-12-31" value={draft.due_date??""} onChange={e=>setDraft({...draft,due_date:e.target.value||null})}/></label></div><div className="status-field"><label htmlFor="task-status">Status</label><Select value={draft.status} onValueChange={v=>setDraft({...draft,status:v as Status})}><SelectTrigger id="task-status" className="w-full"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statusLabels).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select></div><label htmlFor="task-notes">Σημειώσεις <span className="optional">προαιρετικό</span><textarea id="task-notes" maxLength={3000} rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Context, dependencies ή επόμενα βήματα"/></label>{formError&&<p className="form-error" role="alert">{formError} {formError===sessionExpiredMessage&&<a className="underline" href="/">Σύνδεση ξανά</a>}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setTaskOpen(false)}>Ακύρωση</Button><Button type="submit" disabled={saving}>{saving?"Αποθήκευση…":"Αποθήκευση"}</Button></div></form></DialogContent></Dialog></>;
}
